services:
  - type: web
    name: strapi
    env: node
    plan: standard
    buildCommand: yarn install && yarn build
    startCommand: yarn develop
    healthCheckPath: /_health
    autoDeploy: false
    disk:
      name: strapi-uploads
      mountPath: /opt/render/project/src/public/uploads
      sizeGB: 1
    envVars:
      - key: NODE_VERSION
        value: 14.17.0
      - key: NODE_ENV
        value: develop
      - key: DATABASE_URL
        fromDatabase:
          name: strapi
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true

databases:
  - name: strapi2
    plan: free
